### ISSUE TITLE
From where are the sprites coming?

### ISSUE THREAD

**Issue by DataManiac18** [PolturonduckenApp/THE-PTOD-App#5]
I can't seem to find the code for where the sprites (orangutan, viet cong) are defined in the code and given their specific names & pictures. (I'd like to experiment with trying to add a new one to see how sprite addition works)

**Comment by CounterfeitLlama** [comment]
The images are located in the Assests.xcassets folder. It is much easier to add them in Xcode vs. in github.

**Comment by DataManiac18** [comment]
<img width="1399" alt="screen shot 2016-03-13 at 8 25 48 pm" src="https://cloud.githubusercontent.com/assets/17730200/13732464/da1f5e50-e959-11e5-8f66-5aa91e80f592.png">

**Comment by DataManiac18** [comment]
Gratsi!
